name: 'AWS Config'
description: 'Installs AWS CLI and sets up configuration'
inputs:
  role-to-assume-arn:
    description: "ARN for the IAM role to assume to deploy"
    required: true
    type: string
runs:
  using: "composite"
  steps:
     - name: Install AWS CLI
       run: |
         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
         unzip awscliv2.zip
         sudo ./aws/install
         aws --version

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: ${{ inputs.role-to-assume-arn }}
         aws-region: us-west-2