name: Deploy To Staging Environment
on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested, synchronize]
    branches:
      - 'main'
jobs:
  deploy-to-airflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          echo "${{ github.head_ref }}  ---- ${{ github.event.pull_request.head.ref }}"
  detect-file-changes:
    if: github.head_ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: exit 0

  no-new-commits-on-release:
    outputs:
      result: ${{ steps.no-new-commits.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: '1'

      - name: Fetch release branch
        run: git fetch origin release:refs/remotes/origin/release

      - name: Check if no new commits
        id: no-new-commits
        run: |
          COUNT=$(git rev-list --count origin/develop..origin/release)
          echo "Commits only available in release: $COUNT"
          if ["$COUNT" -eq 0];then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

  airflow-env-refresh:
    needs: [deploy-to-airflow, detect-file-changes, no-new-commits-on-release]
    if: ${{ needs.no-new-commits-on-release.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: exit 0

  notify-failure:
    if: ${{ failure() }}
    needs: [detect-file-changes, deploy-to-airflow, airflow-env-refresh]
    runs-on: ubuntu-latest
    steps:
      # why we need this? because we need the PR number in the Slack message, and further we don't need to
      # specify the output variable at job level, as steps in the same job have access to each other's outputs.
      - name: Extract PR number
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pr_number="${{ github.event.pull_request.number }}"
            echo "prefix=PR#" >> $GITHUB_OUTPUT
            echo "value=$pr_number" >> $GITHUB_OUTPUT
          else
            echo "prefix=" >> $GITHUB_OUTPUT
            echo "value=" >> $GITHUB_OUTPUT
          fi
      - name: Set job status emojis
        id: status-emojis
        run: |
          function mark() {
            case "$1" in
              success) echo ":white_check_mark:" ;;
              failure) echo ":x:" ;;
              skipped) echo ":double_vertical_bar:" ;;
              cancelled) echo ":no_entry_sign:" ;;
              *) echo ":grey_question:" ;;
            esac
          }

          deploy=$(mark "${{ needs.deploy-to-airflow.result }}")
          detect=$(mark "${{ needs.detect-file-changes.result }}")
          refresh=$(mark "${{ needs.airflow-env-refresh.result }}")

          echo "deploy=$deploy" >> $GITHUB_OUTPUT
          echo "detect=$detect" >> $GITHUB_OUTPUT
          echo "refresh=$refresh" >> $GITHUB_OUTPUT
      - name: Extract branch and commit metadata
        id: branch-and-commit
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
            echo "commit=" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "commit=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Send Slack message on failure
        uses: slackapi/slack-github-action@v2
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            {
              "channel": "#test-dataset-notifications",
              "text": "🚨 ${{ steps.meta.outputs.prefix }}${{ steps.meta.outputs.value }} Workflow Failed: Deploy to Airflow ${{ inputs.airflow-env-name }} environment",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 ${{ steps.meta.outputs.prefix }}${{ steps.meta.outputs.value }} Workflow Failed: Deploy to Airflow ${{ inputs.airflow-env-name }} environment"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Workflow job status:\n*Deploy to Airflow:* `${{ needs.deploy-to-airflow.result }}` ${{ steps.status-emojis.outputs.deploy }}\n*Detect file changes:* `${{ needs.detect-file-changes.result }}` ${{ steps.status-emojis.outputs.detect }}\n*Airflow env refresh:* `${{ needs.airflow-env-refresh.result }}` ${{ steps.status-emojis.outputs.refresh }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Repository:* <https://github.com/${{ github.repository }}|${{ github.repository }}>\n*Branch that triggered workflow run:* `${{ github.ref_name }}`\n*Commit:* `${{ github.sha }}`"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "View the full logs here:\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|GitHub Actions Run>"
                  }
                }
              ]
            }
