name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
jobs:
  ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@main

      - name: On the PR to develop
        run: echo "PR to develop"
