name: test_workflow.yml
on:
  workflow_dispatch:
env:
  is-staging: false
permissions:
  contents: write
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: exit 0

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: exit 1

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: exit 0

  job4:
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: [ job1, job2, job3 ]
    steps:
      - name: run failure
        run: |
          echo "failure() but still job ran"

  job5:
    runs-on: ubuntu-latest
    if: ${{ needs.job2.result == 'failure' }}
    needs: [ job1, job2, job3 ]
    steps:
      - name: run failure
        run: |
          echo "failure() but still job ran"

  job6:
    runs-on: ubuntu-latest
    if: ${{ env.is-staging }}
    steps:
      - name: run job
        run: |
          echo "job6"

  job7:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [ job1, job6, job3 ]
    steps:
      - name: run failure
        run: |
          echo "skipped but still job ran"

  job8:
    runs-on: ubuntu-latest
    if: ${{ !failure() }}
    needs: [ job1, job6, job3 ]
    steps:
      - name: run failure
        run: |
          echo "skipped but still job ran"

  job9:
    runs-on: ubuntu-latest
    if: ${{ needs.job6.result == 'skipped' }}
    needs: [ job1, job6, job3 ]
    steps:
      - name: run failure
        run: |
          echo "skipped but still ran"
